### ISSUE TITLE
Add Ability to Delete Raids

### ISSUE THREAD

**Issue by ForcedUnknown** [ForcedUnknown/discord-bot#19]
Owner/Creator of the raid + mods/admins should be able to delete raids.

Additionally perhaps for bonus points, if enough people vote down a raid message, perhaps that too deletes it?  Enough people being maybe 5?

**Comment by Googer** [comment]
Implemented, only runnable by mods and admins; if an ordinary user tries running it, it mentions the mod / admin roles to get their attention.
