### ISSUE TITLE
Remove special Master Ball icons for mods and admins

### ISSUE THREAD

**Issue by Tserenteria** [ForcedUnknown/discord-bot#22]
I know this is pretty much an "undo" for the previous add Master Balls issue, but now that we're encoding an entirely different class of data into the pokeball icons, we can't have the master ball symbolizing mod/admin status because it's unrelated to joined/checked in status (and also irrelevant - whether someone is a mod or admin has no bearing on the raid at hand).

This is a UI fix.

**Comment by Googer** [comment]
Current implementation is to show pokeballs for 'interested', greatball for 'coming', ultraball for 'present', premierball for 'complete' statuses, each in their own distinct lists with the status message- no special encoding according to member status.  Intend on adding a ribbon system or the like at some point that can be used to indicate special things, high prestige, etc.
