### ISSUE TITLE
Add !directions command to the raid bot

### ISSUE THREAD

**Issue by Tserenteria** [ForcedUnknown/discord-bot#23]
Add `!directions` (and potential aliases, if applicable) to the raid bot in order to make it easy for users to get Google Maps directions to the gym location.

- This is a redundant function for ease of use and convenience
- I see lots of chatter around folks asking for addresses and directions and pins and whatnot, this should help reduce that.

**Comment by Googer** [comment]
This command now exists on the main-dev branch.  It also spits out a static Google Maps image that is pregenerated (images aren't on this repo but rather https://github.com/Googer/PgP-Data as they add up to about 165MB for all ~2300 gyms).

**Comment by Googer** [comment]
With the main-dev branch now grabbing its map / gym data from the PgP-Data repo, I'll call this fully implemented.  If we wish to make formatting changes to the message at all, so be it, but any changes should be extremely minor at most.
