### ISSUE TITLE
Less messages from channel deletion warning

### ISSUE THREAD

**Issue by ForcedUnknown** [ForcedUnknown/discord-bot#51]
Suggestion:
1 at 10 minutes
1 at 5 minutes
1 at 3 minutes
1 at 2 minutes
1 at 1 minute

**Comment by Googer** [comment]
Let's keep this on the backburner for now; I haven't seen any complaints from users since the switch to 1 at 10 minutes left, followed by 1 every 5 messages after that, so that may already be perfectly sufficient.

**Comment by ForcedUnknown** [comment]
I think what we have now is acceptable, going to close this and if it ever comes back up, we can revisit.
